### ISSUE TITLE
return codes

### ISSUE THREAD

**Issue by oldrich-s** [hardwario/twr-sdk#149]
On any error `return false;` is returned. On no error, `return true;` is returned.

I propose to change it such that on no error `0` is returned. On error a positive number is returned.

As it is now, it is impossible to know where exactly the function fails...

**Comment by hubpav** [comment]
Alright, this is very tempting indeed, but if such change is about to be made, it must be consistent across all SDK. Which means it would break everything (on both application level and inside the libraries). So massive refactoring process would have to be made. It is impossible to do it at this moment. I suggest to close this issue and eventually go some other way around - how about `errno`?

**Comment by czb** [comment]
Looks good ;) if it is what you mean:

http://en.cppreference.com/w/cpp/error/errno

**Comment by hubpav** [comment]
Yes, that's exactly it. It is an old-fashion way and since it is a global variable, just imagine the problems related with it when pthreads appeared :-) Anyway, it works even with pthreads - they handle it in special way - they make it "thread-local". Just BTW...

**Comment by SmejkalJakub** [comment]
We will include this change in the next big SDK refactoring. We will use the `errno.h` library as mentioned before.
