### ISSUE TITLE
Wrong screen dimension handling for 90/270 degree display rotation in twr_gfx.c

### ISSUE THREAD

**Issue by mixicz** [hardwario/twr-sdk#319]
Hi,
while implementing twr_gfx support for waveshare 2.9" e-ink display (128×296 pixels), I noticed wrong behavior for 90 and 270 degree display rotation. It works OK with LCD module as it have square 128×128 display, but it doesn't work for non-square displays.

In particular, problem is in following code snippets from `twr_gfx_draw_pixel()`:

```c
        case TWR_GFX_ROTATION_90:
        {
            tmp = x;
            x = self->_caps.height - 1 - y;
            y = tmp;
            break;
        }
```

```c
        case TWR_GFX_ROTATION_270:
        {
            tmp = y;
            y = self->_caps.width - 1 - x;
            x = tmp;
            break;
        }
```

this should be:

```c
        case TWR_GFX_ROTATION_90:
        {
            tmp = x;
            x = self->_caps.width - 1 - y;
            y = tmp;
            break;
        }
```

```c
        case TWR_GFX_ROTATION_270:
        {
            tmp = y;
            y = self->_caps.height - 1 - x;
            x = tmp;
            break;
        }
```

Logic behind this is, that screen size is relevant to left side of assignment as it represents hardware coordinates. As an example, for my 128×296 display and 270° rotation, writing pixel to _0,0_ coordinates should translate to bottom left which is _0,295_:

original code: y = self->_caps.width - 1 - x = 128 - 1 - 0 = **127**
fixed code: y = self->_caps.height - 1 - x = 296 - 1 - 0 = **295**

**Comment by mixicz** [comment]
I just noticed another bug in same function. Checking pixel coordinates using this code
```c
    if (x >= self->_caps.width || y >= self->_caps.height || x < 0 || y < 0)
    {
        return;
    }
```
must be either done _after_ the switch block doing rotation transformation or reworked to take 90/270° rotation in regard.

**Comment by SmejkalJakub** [comment]
Fix was added to the main SDK branch

https://github.com/hardwario/twr-sdk/commit/11ed3523922a21eefba710bb8c35bbe30707769e
